name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  cache: "node-modules"
                  node-version: "18"

            - name: Install dependencies
              run: npm install

            - name: Check JSDoc Types
              run: npm run lint:typecheck

            - name: Lint ESLint
              run: npm run lint:eslint

            - name: Lint Prettier
              run: npm run lint:prettier

            - name: Check File Changes
              run: echo "Listing changed files:" && git diff --name-only --exit-code && echo "No files changed during lint."
